---
# tasks file for postgresql
- name: install wget
  ansible.builtin.apt:
    name: wget
    state: present
- name: install software certificates
  ansible.builtin.apt:
    name: ca-certificates
    state: present
- name: get certificate, add it to apt-key management
  ansible.builtin.command:
    cmd: wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  ignore_errors: true
- name: create configuration file
  ansible.builtin.command:
    cmd: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
- name: update apt repository
  ansible.builtin.apt:
    update_cache: yes
- name: install postgresql
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
- name: check postgresql status
  ansible.builtin.command:
    cmd: systemctl status postgresql
  register: postgresql_status
  tags: postgresql_status
- name: Print postgresql status
  ansible.builtin.debug:
    var: postgresql_status.stdout_lines
  tags: postgresql_status
