---
# main list of role tasks
- name: make sure chrony is installed
  package:
    name: chrony
    state: present
- name: template out the ntp configuration
  template:
    src: chrony.j2
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
  notify: restart chrony daemon
- name: set timezone
  timezone:
    name: "Europe/Istanbul"
