---
# tasks file for kibana
- name: Install kibana 
  apt:
    name: kibana
    state: latest
- name: enable kibana
  command: sudo systemctl enable kibana
- name: start kibana
  service:
    name: kibana
    state: started