# https://samber.github.io/awesome-prometheus-alerts/rules.html#kubernetes

groups:
- name: KubePodPVs
  rules:
    - alert: KubernetesPersistentvolumeError
      expr: kube_persistentvolume_status_phase{phase=~"Failed|Pending", job="kube-state-metrics"} > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Kubernetes PersistentVolume error (instance {{ $labels.instance }})
        description: |
          Persistent volume {{ $labels.persistentvolume }} is in bad state\n
          
          VALUE = {{ $value }}

          COUNTRY: {{ $labels.country }}
          ENVIRONMENT: {{ $labels.environment }}
          NAMESPACE: {{ $labels.namespace }}

    - alert: KubernetesVolumeOutOfDiskSpace
      expr: kubelet_volume_stats_available_bytes / kubelet_volume_stats_capacity_bytes * 100 < 10
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Kubernetes Volume out of disk space (instance {{ $labels.instance }})
        description: |
          Volume is almost full (< 10% left)

          VALUE = {{ $value }}

          COUNTRY: {{ $labels.country }}
          ENVIRONMENT: {{ $labels.environment }}
          NAMESPACE: {{ $labels.namespace }}

    - alert: KubernetesPersistentvolumeclaimPending
      expr: kube_persistentvolumeclaim_status_phase{phase="Pending"} == 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Kubernetes PersistentVolumeClaim pending (instance {{ $labels.instance }})
        description: |
          PersistentVolumeClaim {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} is pending
          
          VALUE = {{ $value }}

          COUNTRY: {{ $labels.country }}
          ENVIRONMENT: {{ $labels.environment }}
          NAMESPACE: {{ $labels.namespace }}
