global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["172.31.27.189:9090"]

  - job_name: "node-exporter"
    ec2_sd_configs:
      - region: eu-central-1
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_private_ip]
        target_label: private_ip

  - job_name: "ke-stage-federation"
    scrape_interval: "30s"
    honor_labels: true
    metrics_path: /federate
    params:
      'match[]':
         - '{job=~"node.*|cad.*|blackbox.*|yace.*|kube.*|rab.*"}'
    static_configs:
      - targets: ['ke-stage-cluster-metrics.kokonetworks.com']
        labels:
          country: "kenya"
          environment: "stage"
          platform: "k8s"