---
# tasks file for elasticsearch
- name: import elasticsearch public GPG key into APT
  shell: curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch |sudo gpg --dearmor -o /usr/share/keyrings/elastic.gpg
- name: add elasticsearch source list to source.list.d
  command: echo "deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list
- name: update package repositories
  become: true
  apt:
    update_cache: yes
- name: restrict elasticsearch access
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^network\.host'
    line: 'network.host: localhost'
    owner: ubuntu
    group: ubuntu
    mode: '0644'
- name: install elasticsearch
  apt:
    name: elasticsearch
    state: latest
- name: start elasticsearch
  service:
    name: elasticsearch
- name: enable elasticsearch
  command: sudo systemctl enable elasticsearch
